export default {
    ASSIGN: "ASSIGN",
    COMMA: "COMMA",
    CONVERT: "CONVERT",
    DEFINITE_ARTICLE: "DEFINITE_ARTICLE",
    FORWARD_SLASH: "FORWARD_SLASH",
    HEX: "HEX",
    IDENTIFIER: "IDENTIFIER",
    INDEFINITE_ARTICLE: "INDEFINITE_ARTICLE",
    IS: "IS",
    NUMBER: "NUMBER",
    PERIOD: "PERIOD",
    SEMICOLON: "SEMICOLON",
    TEXT: "TEXT",
    TO: "TO",
    WRITE: "WRITE"
}
