export default {
    ASSIGN: "ASSIGN",
    COMMA: "COMMA",
    CONVERT: "CONVERT",
    FORWARDSLASH: "FORWARDSLASH",
    HEX: "HEX",
    IDENTIFIER: "IDENTIFIER",
    INDEFINITE_ARTICLE: "INDEFINITE_ARTICLE",
    IS: "IS",
    NUMBER: "NUMBER",
    PERIOD: "PERIOD",
    SEMICOLON: "SEMICOLON",
    TEXT: "TEXT",
    WRITE: "WRITE"
}
